site_name: Cuihua Xia
site_url: https://touchumind.com
nav:
  - Home: index.md
  - Projects: projects.md
  - Software: software.md
  - Publications: publications.md
  - News: news.md
  - Blogs: blogs.md
theme:
  name: material  #readthedocs
  features:
    - navigation.tabs
    # - navigation.footer
    - navigation.top
    - navigation.tracking
    - search.highlight
    - content.code.annotate
    - content.code.copy
  logo: logo.png
  # favicon: assets/favicon.png
  font:
    text: Roboto
    code: Roboto Mono
copyright: Copyright &copy; 2020 - 2026 <a href="https://touchumind.com/">Cuihua Xia</a>
extra:
  analytics:
    provider: google
    property: G-EJR22ZQ12Q
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CuihuaXia
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/CuihuaXia
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0002-6915-3385
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com/citations?hl=en&user=tCGP6ZkAAAAJ
